Update model UML
AY2425S1-CS2103T-T16-4/tp pull request #115
Opened 2024-10-23 04:21 UTC by Ansel-Ch

Closes #114

2024-10-23 04:41 UTC, Ansel-Ch commented
![image](https://github.com/user-attachments/assets/97ebeaff-d80b-49be-9d84-90ed6d85b5e5)
![image](https://github.com/user-attachments/assets/a6b785c4-93bb-4301-b2d5-01e4f7cd0885)
Here are the images for yall to check.

2024-10-24 05:49 UTC, gnoossk requested changes

2024-10-24 05:49 UTC, gnoossk commented on docs/diagrams/model/ModelClassDiagram.puml
> +Student *--> Assignment
Student should also include the List of AttendanceRecord, with the new Attendance Model. Other than that, LGTM.

2024-10-24 06:10 UTC, gnoossk approved these changes

2024-10-24 06:10 UTC, merged